monolog:
    channels:
        - security
        - doctrine
        - request
        - presentation
        - application
        - domain
        - infrastructure
    handlers:
        default:
            type:   stream
            path:   '%kernel.logs_dir%/%kernel.environment%.log'
            level:  debug
            channels: [!security, !doctrine, !request, !presentation, !application, !domain, !infrastructure]
        doctrine:
            #bubble: false
            #action_level: DEBUG  #DEBUG INFO NOTICE WARNING ERROR CRITICAL ALERT EMERGENCY
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.doctrine.log
            level: debug
            channels: [doctrine]
        request:
            #bubble: false
            #action_level: DEBUG  #DEBUG INFO NOTICE WARNING ERROR CRITICAL ALERT EMERGENCY
            type:  stream
            path: '%kernel.logs_dir%/%kernel.environment%_request.log'
            level: debug
            channels: [request]
        presentation:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.presentation.log
            level: debug
            channels: [presentation]
        application:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.application.log
            level: debug
            channels: [application]
        domain:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.domain.log
            level: debug
            channels: [domain]
        infrastructure:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.infrastructure.log
            level: debug
            channels: [infrastructure]
#        socket:
#            type: socket
#            connection_string: udp://127.0.0.1:5565
#            handler:      dirisi.monolog.handler.socket
