imports:
    - { resource: config_demoapi_orm.yml }
    - { resource: config_monolog.yml }

framework:
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %kernel.debug%
    intercept_redirects: false

