#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

//var_dump($_SERVER);exit;

set_time_limit(0);

require_once __DIR__.'/autoload.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Dotenv\Dotenv;

//load environment variables Please Note: it don't overwrite existing one
if(file_exists(__DIR__ . '/../../env/.env')) {
    $dotenv = new Dotenv(__DIR__ . '/../../env/');
    $dotenv->load();
}

$input = new ArgvInput();
$kernel = new AppKernel($_SERVER['SYMFONY__PROJECT__ENV'], (bool)$_SERVER['SYMFONY__PROJECT__DEBUG']);
$application = new Application($kernel);
$application->run($input);
